import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:http/http.dart' as http;
import 'package:xml/xml.dart';
import '../models/video_info.dart';

class VideoExtractorService {
  final _yt = YoutubeExplode();

  Future<VideoInfo> extract(String url) async {
    final uri = Uri.tryParse(url.trim());
    if (uri == null || !uri.hasScheme || !uri.scheme.startsWith('http')) {
      throw Exception(
        'Please enter a valid URL starting with http:// or https://',
      );
    }

    final host = uri.host.toLowerCase();
    if (host.contains('youtube.com') || host.contains('youtu.be') || host.contains('m.youtube.com')) {
      // Validate that the URL actually contains a video identifier.
      final hasVideoId = uri.queryParameters.containsKey('v') ||
          host.contains('youtu.be') && uri.pathSegments.isNotEmpty ||
          uri.path.contains('/shorts/') ||
          uri.path.contains('/embed/') ||
          uri.path.contains('/live/');
      if (!hasVideoId) {
        throw Exception(
          'This YouTube URL does not contain a video. '
          'Please paste a link to a specific video.',
        );
      }
      return _extractYouTube(url);
    }

    // HLS manifest — parse for quality levels
    if (url.toLowerCase().contains('.m3u8')) {
      return _extractHls(url);
    }
    // DASH manifest — parse for quality levels
    if (RegExp(r'\.mpd(\?|#|$)', caseSensitive: false).hasMatch(url)) {
      return _extractDash(url);
    }

    return _extractDirect(url);
  }

  Future<VideoInfo> _extractYouTube(String url) async {
    final video = await _yt.videos.get(url);

    // Fetch streams and captions in parallel — both only need video.id.
    final results = await Future.wait([
      _yt.videos.streamsClient.getManifest(video.id),
      _extractCaptions(video.id),
    ]);
    final manifest = results[0] as StreamManifest;
    final subtitles = results[1] as List<SubtitleTrack>;

    final formats = <StreamFormat>[];

    // Muxed (video + audio in one stream) — always prefer these.
    // sortByVideoQuality() returns ascending; reverse to put highest first.
    final muxed = manifest.muxed.sortByVideoQuality().toList().reversed.toList();
    for (int i = 0; i < muxed.length; i++) {
      final s = muxed[i];
      formats.add(StreamFormat(
        id: 'muxed_$i',
        label: '${s.videoResolution.height}p · mp4 · video+audio',
        url: s.url.toString(),
        height: s.videoResolution.height,
        hasAudio: true,
        filesize: s.size.totalBytes,
      ));
    }

    // If no muxed streams exist (rare), fall back to video-only adaptive.
    if (formats.isEmpty) {
      final adaptive = manifest.videoOnly.sortByVideoQuality().toList().reversed.toList();
      for (int i = 0; i < adaptive.length; i++) {
        final s = adaptive[i];
        formats.add(StreamFormat(
          id: 'video_$i',
          label: '${s.videoResolution.height}p · ${s.container.name} · video only ⚠',
          url: s.url.toString(),
          height: s.videoResolution.height,
          hasAudio: false,
          filesize: s.size.totalBytes,
        ));
      }
    }

    return VideoInfo(
      title: video.title,
      thumbnailUrl: video.thumbnails.highResUrl,
      durationSeconds: video.duration?.inSeconds,
      uploader: video.author,
      formats: formats,
      subtitles: subtitles,
    );
  }

  /// Fetches all available closed-caption tracks and converts them to SRT.
  Future<List<SubtitleTrack>> _extractCaptions(VideoId videoId) async {
    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);
      final tracks = <SubtitleTrack>[];

      for (final info in manifest.tracks) {
        try {
          final track = await _yt.videos.closedCaptions.get(info);
          final srt = _captionsToSrt(track.captions);
          tracks.add(SubtitleTrack(
            language: info.language.code,
            label: '${info.language.name}${info.isAutoGenerated ? ' (auto)' : ''}',
            srtContent: srt,
          ));
        } catch (_) {
          // Skip tracks that fail to download.
        }
      }
      return tracks;
    } catch (_) {
      return [];
    }
  }

  /// Converts a list of ClosedCaption objects into SRT subtitle format.
  String _captionsToSrt(List<ClosedCaption> captions) {
    final buf = StringBuffer();
    for (int i = 0; i < captions.length; i++) {
      final c = captions[i];
      final start = c.offset;
      final end = start + c.duration;
      buf.writeln(i + 1);
      buf.writeln('${_srtTime(start)} --> ${_srtTime(end)}');
      buf.writeln(c.text);
      buf.writeln();
    }
    return buf.toString();
  }

  String _srtTime(Duration d) {
    final h = d.inHours.toString().padLeft(2, '0');
    final m = (d.inMinutes % 60).toString().padLeft(2, '0');
    final s = (d.inSeconds % 60).toString().padLeft(2, '0');
    final ms = (d.inMilliseconds % 1000).toString().padLeft(3, '0');
    return '$h:$m:$s,$ms';
  }

  Future<VideoInfo> _extractDirect(String url) async {
    final isLikelyVideo = RegExp(
      r'\.(mp4|m3u8|webm|mkv|avi|mov|flv|ts|mpd|m4v|3gp|wmv)(\?|#|$)',
      caseSensitive: false,
    ).hasMatch(url);

    if (!isLikelyVideo) {
      try {
        final response = await http.head(Uri.parse(url)).timeout(const Duration(seconds: 8));
        final ct = response.headers['content-type'] ?? '';
        if (!ct.contains('video/') &&
            !ct.contains('audio/') &&
            !ct.contains('application/x-mpegurl') &&
            !ct.contains('application/vnd.apple.mpegurl') &&
            !ct.contains('application/dash+xml') &&
            !ct.contains('application/octet-stream')) {
          throw Exception(
            'This URL doesn\'t appear to be a direct video link.\n\n'
            'Supported:\n'
            '• YouTube links (full URL or short URL)\n'
            '• Direct video files (.mp4, .m3u8, .webm, .mkv, etc.)\n\n'
            'Tip: Use the Browser tab to find and detect video URLs on any page.',
          );
        }
      } catch (e) {
        if (e.toString().contains('Supported:')) rethrow;
        // Swallow HEAD errors (server may not allow HEAD) and try anyway
      }
    }

    final uri = Uri.parse(url);
    // Decode percent-encoded characters (e.g. %20 → space) for display.
    final raw = uri.pathSegments.isNotEmpty
        ? Uri.decodeComponent(uri.pathSegments.last.split('?').first)
        : '';
    final filename = raw.isNotEmpty ? raw : 'Direct Stream';

    return VideoInfo(
      title: filename.isNotEmpty ? filename : 'Direct Stream',
      formats: [
        StreamFormat(
          id: 'direct',
          label: 'Direct stream',
          url: url,
          height: 0,
          hasAudio: true,
        ),
      ],
    );
  }

  void dispose() => _yt.close();

  // ── HLS (.m3u8) manifest parsing ──────────────────────────────────────────

  Future<VideoInfo> _extractHls(String url) async {
    try {
      final response = await http.get(Uri.parse(url))
          .timeout(const Duration(seconds: 10));
      if (response.statusCode != 200) return _extractDirect(url);

      final body = response.body;
      final formats = <StreamFormat>[];
      final lines = body.split('\n');
      final baseUri = Uri.parse(url);

      for (int i = 0; i < lines.length; i++) {
        final line = lines[i].trim();
        if (line.startsWith('#EXT-X-STREAM-INF:')) {
          // Parse bandwidth and resolution
          final bwMatch = RegExp(r'BANDWIDTH=(\d+)').firstMatch(line);
          final resMatch = RegExp(r'RESOLUTION=(\d+)x(\d+)').firstMatch(line);
          final bandwidth = int.tryParse(bwMatch?.group(1) ?? '') ?? 0;
          final height = int.tryParse(resMatch?.group(2) ?? '') ?? 0;

          // Next non-empty, non-comment line is the stream URL
          String streamUrl = '';
          for (int j = i + 1; j < lines.length; j++) {
            final next = lines[j].trim();
            if (next.isEmpty || next.startsWith('#')) continue;
            streamUrl = next;
            break;
          }
          if (streamUrl.isEmpty) continue;

          // Make absolute URL
          if (!streamUrl.startsWith('http')) {
            streamUrl = baseUri.resolve(streamUrl).toString();
          }

          final label = height > 0
              ? '${height}p · ${(bandwidth / 1000000).toStringAsFixed(1)} Mbps'
              : '${(bandwidth / 1000).toStringAsFixed(0)} kbps';

          formats.add(StreamFormat(
            id: 'hls_$i',
            label: label,
            url: streamUrl,
            height: height,
            hasAudio: true,
          ));
        }
      }

      // Sort by height descending
      formats.sort((a, b) => b.height.compareTo(a.height));

      // If no stream variants found, it's a single-quality stream
      if (formats.isEmpty) {
        formats.add(StreamFormat(
          id: 'hls_direct',
          label: 'HLS stream',
          url: url,
          height: 0,
          hasAudio: true,
        ));
      }

      final filename = baseUri.pathSegments.isNotEmpty
          ? Uri.decodeComponent(baseUri.pathSegments.last.split('?').first)
          : 'HLS Stream';

      return VideoInfo(
        title: filename,
        formats: formats,
      );
    } catch (e) {
      return _extractDirect(url);
    }
  }

  // ── DASH (.mpd) manifest parsing ──────────────────────────────────────────

  Future<VideoInfo> _extractDash(String url) async {
    try {
      final response = await http.get(Uri.parse(url))
          .timeout(const Duration(seconds: 10));
      if (response.statusCode != 200) return _extractDirect(url);

      final doc = XmlDocument.parse(response.body);
      final baseUri = Uri.parse(url);
      int bestHeight = 0;
      int bestBandwidth = 0;
      for (final rep in doc.findAllElements('Representation')) {
        final height = int.tryParse(rep.getAttribute('height') ?? '') ?? 0;
        final bandwidth = int.tryParse(rep.getAttribute('bandwidth') ?? '') ?? 0;
        if (height > bestHeight) bestHeight = height;
        if (bandwidth > bestBandwidth) bestBandwidth = bandwidth;
      }

      final label = bestHeight > 0
          ? 'DASH stream · up to ${bestHeight}p'
          : bestBandwidth > 0
              ? 'DASH stream · ${(bestBandwidth / 1000000).toStringAsFixed(1)} Mbps'
              : 'DASH stream';

      final formats = [
        StreamFormat(
          id: 'dash_direct',
          label: label,
          url: url,
          height: bestHeight,
          hasAudio: true,
        ),
      ];

      final filename = baseUri.pathSegments.isNotEmpty
          ? Uri.decodeComponent(baseUri.pathSegments.last.split('?').first)
          : 'DASH Stream';

      return VideoInfo(title: filename, formats: formats);
    } catch (e) {
      return _extractDirect(url);
    }
  }
}
