import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:http/http.dart' as http;
import '../models/video_info.dart';

class VideoExtractorService {
  final _yt = YoutubeExplode();

  Future<VideoInfo> extract(String url) async {
    final uri = Uri.tryParse(url.trim());
    if (uri == null || !uri.hasScheme || !uri.scheme.startsWith('http')) {
      throw Exception(
        'Please enter a valid URL starting with http:// or https://',
      );
    }

    final host = uri.host.toLowerCase();
    if (host.contains('youtube.com') || host.contains('youtu.be')) {
      return _extractYouTube(url);
    }
    return _extractDirect(url);
  }

  Future<VideoInfo> _extractYouTube(String url) async {
    final video = await _yt.videos.get(url);
    final manifest = await _yt.videos.streamsClient.getManifest(video.id);

    final formats = <StreamFormat>[];

    // Muxed (video + audio in one stream) — always prefer these.
    // sortByVideoQuality() returns ascending; reverse to put highest first.
    final muxed = manifest.muxed.sortByVideoQuality().toList().reversed.toList();
    for (int i = 0; i < muxed.length; i++) {
      final s = muxed[i];
      formats.add(StreamFormat(
        id: 'muxed_$i',
        label: '${s.videoResolution.height}p · mp4 · video+audio',
        url: s.url.toString(),
        height: s.videoResolution.height,
        hasAudio: true,
        filesize: s.size.totalBytes,
      ));
    }

    // If no muxed streams exist (rare), fall back to video-only adaptive.
    if (formats.isEmpty) {
      final adaptive = manifest.videoOnly.sortByVideoQuality().toList().reversed.toList();
      for (int i = 0; i < adaptive.length; i++) {
        final s = adaptive[i];
        formats.add(StreamFormat(
          id: 'video_$i',
          label: '${s.videoResolution.height}p · ${s.container.name} · video only ⚠',
          url: s.url.toString(),
          height: s.videoResolution.height,
          hasAudio: false,
          filesize: s.size.totalBytes,
        ));
      }
    }

    // ── Subtitles / Closed Captions ─────────────────────────────────────────
    final subtitles = await _extractCaptions(video.id);

    return VideoInfo(
      title: video.title,
      thumbnailUrl: video.thumbnails.highResUrl,
      durationSeconds: video.duration?.inSeconds,
      uploader: video.author,
      formats: formats,
      subtitles: subtitles,
    );
  }

  /// Fetches all available closed-caption tracks and converts them to SRT.
  Future<List<SubtitleTrack>> _extractCaptions(VideoId videoId) async {
    try {
      final manifest = await _yt.videos.closedCaptions.getManifest(videoId);
      final tracks = <SubtitleTrack>[];

      for (final info in manifest.tracks) {
        try {
          final track = await _yt.videos.closedCaptions.get(info);
          final srt = _captionsToSrt(track.captions);
          tracks.add(SubtitleTrack(
            language: info.language.code,
            label: '${info.language.name}${info.isAutoGenerated ? ' (auto)' : ''}',
            srtContent: srt,
          ));
        } catch (_) {
          // Skip tracks that fail to download.
        }
      }
      return tracks;
    } catch (_) {
      return [];
    }
  }

  /// Converts a list of ClosedCaption objects into SRT subtitle format.
  String _captionsToSrt(List<ClosedCaption> captions) {
    final buf = StringBuffer();
    for (int i = 0; i < captions.length; i++) {
      final c = captions[i];
      final start = c.offset;
      final end = start + c.duration;
      buf.writeln(i + 1);
      buf.writeln('${_srtTime(start)} --> ${_srtTime(end)}');
      buf.writeln(c.text);
      buf.writeln();
    }
    return buf.toString();
  }

  String _srtTime(Duration d) {
    final h = d.inHours.toString().padLeft(2, '0');
    final m = (d.inMinutes % 60).toString().padLeft(2, '0');
    final s = (d.inSeconds % 60).toString().padLeft(2, '0');
    final ms = (d.inMilliseconds % 1000).toString().padLeft(3, '0');
    return '$h:$m:$s,$ms';
  }

  Future<VideoInfo> _extractDirect(String url) async {
    final isLikelyVideo = url.contains('.mp4') ||
        url.contains('.m3u8') ||
        url.contains('.webm') ||
        url.contains('.mkv') ||
        url.contains('.avi') ||
        url.contains('.mov');

    if (!isLikelyVideo) {
      try {
        final response = await http.head(Uri.parse(url)).timeout(const Duration(seconds: 8));
        final ct = response.headers['content-type'] ?? '';
        if (!ct.contains('video/') &&
            !ct.contains('application/x-mpegurl') &&
            !ct.contains('application/vnd.apple.mpegurl') &&
            !ct.contains('application/octet-stream')) {
          throw Exception(
            'This URL doesn\'t appear to be a direct video link.\n'
            'Supported: YouTube, or direct .mp4 / .m3u8 / .webm URLs.',
          );
        }
      } catch (e) {
        if (e.toString().contains('Supported:')) rethrow;
        // Swallow HEAD errors (server may not allow HEAD) and try anyway
      }
    }

    final uri = Uri.parse(url);
    // Decode percent-encoded characters (e.g. %20 → space) for display.
    final raw = uri.pathSegments.isNotEmpty
        ? Uri.decodeComponent(uri.pathSegments.last.split('?').first)
        : '';
    final filename = raw.isNotEmpty ? raw : 'Direct Stream';

    return VideoInfo(
      title: filename.isNotEmpty ? filename : 'Direct Stream',
      formats: [
        StreamFormat(
          id: 'direct',
          label: 'Direct stream',
          url: url,
          height: 0,
          hasAudio: true,
        ),
      ],
    );
  }

  void dispose() => _yt.close();
}
